# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table rating (
  id                            bigint generated by default as identity not null,
  rating                        varchar(255),
  parent_recipe_id              bigint,
  version                       bigint not null,
  when_created                  timestamp not null,
  when_modified                 timestamp not null,
  constraint pk_rating primary key (id)
);

create table recipes (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  time                          varchar(255),
  type                          varchar(255),
  pasos_id                      bigint,
  version                       bigint not null,
  when_created                  timestamp not null,
  when_modified                 timestamp not null,
  constraint uq_recipes_pasos_id unique (pasos_id),
  constraint pk_recipes primary key (id)
);

create table steps (
  id                            bigint generated by default as identity not null,
  pasos                         varchar(255),
  version                       bigint not null,
  when_created                  timestamp not null,
  when_modified                 timestamp not null,
  constraint pk_steps primary key (id)
);

create index ix_rating_parent_recipe_id on rating (parent_recipe_id);
alter table rating add constraint fk_rating_parent_recipe_id foreign key (parent_recipe_id) references recipes (id) on delete restrict on update restrict;

alter table recipes add constraint fk_recipes_pasos_id foreign key (pasos_id) references steps (id) on delete restrict on update restrict;


# --- !Downs

alter table rating drop constraint if exists fk_rating_parent_recipe_id;
drop index if exists ix_rating_parent_recipe_id;

alter table recipes drop constraint if exists fk_recipes_pasos_id;

drop table if exists rating;

drop table if exists recipes;

drop table if exists steps;

