# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table recipes (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  pasos_id                      bigint,
  version                       bigint not null,
  when_created                  timestamp not null,
  when_modified                 timestamp not null,
  constraint uq_recipes_pasos_id unique (pasos_id),
  constraint pk_recipes primary key (id)
);

create table steps (
  id                            bigint generated by default as identity not null,
  pasos                         varchar(255),
  version                       bigint not null,
  when_created                  timestamp not null,
  when_modified                 timestamp not null,
  constraint pk_steps primary key (id)
);

alter table recipes add constraint fk_recipes_pasos_id foreign key (pasos_id) references steps (id) on delete restrict on update restrict;


# --- !Downs

alter table recipes drop constraint if exists fk_recipes_pasos_id;

drop table if exists recipes;

drop table if exists steps;

